version: "2.1"
services:
  # This service MUST have the name "kdc-kadmin" otherwise every kerberos client won't be able to talk with the KDC.
  # If you would like to change the name edit the file configureKerberosClient.sh and change the configurations
  # "kdc" and "admin_server" in the /etc/krb5.conf section.
  kdc-kadmin:
    build: ./kerberos-container/kdc-kadmin
    env_file: ./kerberos-container/kerberos.env
    network_mode: bridge
    dns_search: example.com
    volumes:
      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - /dev/urandom:/dev/random
  hadoop:
    build: ./hadoop-container
    network_mode: bridge
    dns_search: example.com
    hostname: hadoop.example.com
    links:
      - "kdc-kadmin:kdc.example.com"
      - "splunk:splunk.example.com"
      - "kdc-kadmin:kdc"
      - "splunk:splunk"
      - "kdc-kadmin:kerberos"
      - "kdc-kadmin:kerberos.example.com"
    ports:
      - 50070:50070
  splunk:
    build: ./splunk-container
    network_mode: bridge
    dns_search: example.com
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Password123 
    ports:
      - 8000:8000

networks:
  bridge:
    enable_ipv6: false
#  kerberos-client:
#    build: ./kerberos-client
#    env_file: kerberos.env
#    depends_on:
#      - kdc-kadmin

# NOTE:
#  "env_file: kerberos.env" is optional.
#  In case no .env file is supplied, nor any environment variable is set, the following values will be used:
#   REALM=EXAMPLE.COM
#   SUPPORTED_ENCRYPTION_TYPES=aes256-cts-hmac-sha1-96:normal
#   KADMIN_PRINCIPAL=kadmin/admin
#   KADMIN_PASSWORD=MITiys4K5
