apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyter-notebook-config
data:
  storage_path.py: |
    from s3contents import S3ContentsManager
    from IPython.lib import passwd
    c = get_config()
    # Startup auth Token
    c.NotebookApp.password = passwd("secret-password@jupyter-server")
    # S3 Object Storage Configuration
    c.NotebookApp.contents_manager_class = S3ContentsManager
    c.S3ContentsManager.access_key_id = "oaktree"
    c.S3ContentsManager.secret_access_key = "secert-token@object-storage"
    c.S3ContentsManager.endpoint_url = "http://object-storage:9000"
    c.S3ContentsManager.bucket = "jupyter.oak-tree.tech"
    c.S3ContentsManager.prefix = "notebooks"
